#!/bin/sh

CLASSPATH=lib/amazon-simple-db-2009-04-15-java-library.jar:lib/commons-httpclient-3.0.1.jar:lib/commons-logging-1.1.jar:lib/commons-codec-1.3.jar:lib/json_simple-1.1.jar:.

java -cp $CLASSPATH SimpleDBLoader $@
